name: Deploy to k8s
run-name: deploy-to-k8s
on:
  workflow_call:
    inputs:
      envs-context:
        description: "Enviroments pass as context"
        required: false
        default: ""
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: abielalejandro/github-actions-variables/action1@main
        with:
          who-to-greet: 'Mona the Octocat'
          env-vars: ${{ inputs.envs-context }}