name: Deploy to k8s
run-name: deploy-to-k8s
on:
  workflow_call:
    inputs:
      envs-context:
        description: "Enviroments pass as context"
        required: false
        default: ""
        type: string
jobs:
    steps:
        - uses: abielalejandro/github-actions-variables/action1@main
          with:
           who-to-greet: 'Mona the Octocat'
           env-vars: "${{ toJson(inputs.envs-context) }}"