name: Workflow Demo

on: 
  push:
  workflow_dispatch:

env:
  ROMERD: "2234"

jobs:
  pre:
    outputs:
     token: ${{ steps.uno.outputs.token }}
    runs-on: ubuntu-latest
    steps:
      - name: uno
        id: uno
        run: echo "token=123">> $GITHUB_OUTPUT
      - name: dos
        run: echo "${{ toJson(steps.uno.outputs)}}"
  hello_world_job:
    needs: [ pre ]
    uses: abielalejandro/github-actions-variables/.github/workflows/otro.yml@main
    with:
      envs-context: "${{ toJson(needs.pre.outputs) }}"