name: Workflow Demo

on: 
  push:
  workflow_dispatch:

env:
  ROMERD: "2234"

jobs:
  hello_world_job:
    uses: abielalejandro/github-actions-variables/.github/workflows/otro.yml@main
    with:
      envs-context: "${{ toJson(vars) }}"