name: Workflow Demo

on: 
  push:
  workflow_dispatch:

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}
  ROMERD: "2234"

jobs:
  build:
    runs-on: ubuntu-latest
  hello_world_job:
    uses: abielalejandro/github-actions-variables/.github/workflows/otro.yml
    with:
      who-to-greet: 'Mona the Octocat'
      env-vars: "${{ toJson(env) }}"