name: Workflow Demo

on: 
  push:
  workflow_dispatch:

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID

  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - run: |
           echo ${{ env.ACCESS_ID }}
           echo ${{ vars.ACCESS_ID }}
      - run: |
           echo ${{ fromJson(env) }}
        shell: bash
      - id: foo
        env: 
          APP_RANDOM: ${{ env.APP_RANDOM }}
        uses: abielalejandro/github-actions-variables/action1@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash